[project]
name = "h3"
version = "0.1.0"
description = "Features for h3 community"
requires-python = ">=3.12,<4"
dependencies = ["discord-py (>=2.4,<3.0)", "python-dotenv (>=1.0,<2.0)"]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"